data:
  cleaned_df: data\interim\cleaned_df.csv
  raw_df: data\raw\predictive_maintenance.csv
  test_data: data\processed\test_processed.csv
  train_data: data\processed\train_processed.csv
model:
  knn: models\knn.pkl
  random_forest: models\random_forest.pkl
  xgboost: models\xgboost.pkl
