stages:
  
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - data/raw/predictive_maintenance.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim/cleaned_df.csv
  
  data_processing:
    cmd: python -m src.features.build_features
    deps:
    - data/interim/cleaned_df.csv
    - src/features/build_features.py
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
  
  model_tuning:
    cmd: python -m src.models.model_tuning.py
    deps:
    - config.yaml
    - src/models/model_tuning.py
    - data/processed/train_processed.csv
    - params.yaml
    outs:
    - models/
