stages:
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - data/raw/predictive_maintenance.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim/cleaned_df.csv

  data_processing:
    cmd: python -m src.features.build_features
    deps:
    - data/interim/cleaned_df.csv
    - src/features/build_features.py
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
    - models/target_encodings.pkl

  train_model:
    cmd: python -m src.models.train_model
    deps:
    - data/processed/train_processed.csv
    - src/models/train_model.py
    outs:
    - models/scale.pkl
    metrics:
    - metrics.json:
        cache: false
  predit_model:
    cmd: python -m src.models.predict_model
    deps:
    - data/processed/test_processed.csv
    - models/random_forest.pkl
    - src/models/predict_model.py
    outs:
    - confusion-failure_type.png
    - confusion-target.png
    metrics:
    - test_metric-target.json:
        cache: false
    - test_metric-failure_type.json: 
        cache: false
